--- #YAML:1.0
name:                Acme-Note
version:             0.1
abstract:            Make a mental note for programming style
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Adriano R. Ferreira <ferreira@cpan.org>
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
recommends:
    Test::Pod:                     1.18
    Test::Pod::Coverage:           1.04
