--- #YAML:1.0
name:                Acme-Note
version:             0.5
abstract:            Make a mental note for programming style
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Term::ANSIColor:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Adriano R. Ferreira <ferreira@cpan.org>
recommends:
    Test::Pod:                     1.18
    Test::Pod::Coverage:           1.04
